deployment:
  tasks:
    - export DEPLOYPATH=/home/mirazic1/makasana.kolatech.co.ke/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R migrations $DEPLOYPATH
    - /bin/cp run.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp passenger_wsgi.py $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
