deployment:
  tasks:
    - export DEPLOYPATH=/home/mirazic1/makasanaconsultancy/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R migrations $DEPLOYPATH
    - /bin/cp run.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp passenger_wsgi.py $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/touch $DEPLOYPATH/tmp/restart.txt || (/bin/mkdir -p $DEPLOYPATH/tmp && /bin/touch $DEPLOYPATH/tmp/restart.txt)
